name: 'games_analyse'
version: '1.0.0'
config-version: 2

profile: 'games_analyse'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  games_analyse:
    staging:
      +materialized: view
    marts:
      +materialized: table
